CREATE TABLE "sqfast"."GEN_TABLE"
(
"TABLE_ID" BIGINT IDENTITY(37, 1) NOT NULL,
"TABLE_NAME" VARCHAR(200) DEFAULT '',
"TABLE_COMMENT" VARCHAR(500) DEFAULT '',
"SUB_TABLE_NAME" VARCHAR(64),
"SUB_TABLE_FK_NAME" VARCHAR(64),
"CLASS_NAME" VARCHAR(100) DEFAULT '',
"TPL_CATEGORY" VARCHAR(200) DEFAULT 'crud',
"TPL_WEB_TYPE" VARCHAR(30) DEFAULT '',
"PACKAGE_NAME" VARCHAR(100),
"MODULE_NAME" VARCHAR(30),
"BUSINESS_NAME" VARCHAR(30),
"FUNCTION_NAME" VARCHAR(50),
"FUNCTION_AUTHOR" VARCHAR(50),
"GEN_TYPE" CHAR(1) DEFAULT '0',
"GEN_PATH" VARCHAR(200) DEFAULT '/',
"OPTIONS" VARCHAR(1000),
"CREATE_BY" VARCHAR(64) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500),
"CONTROLLER_PACKAGE_NAME" VARCHAR(255),
"CONTROLLER_MODULE_NAME" VARCHAR(255),
"EDIT_TYPE" CHAR(1),
NOT CLUSTER PRIMARY KEY("TABLE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."GEN_TABLE" IS '代码生成业务表';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."BUSINESS_NAME" IS '生成业务名';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."CLASS_NAME" IS '实体类名称';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."CONTROLLER_MODULE_NAME" IS 'controller生成模块名';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."CONTROLLER_PACKAGE_NAME" IS 'controller生成包路径';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."EDIT_TYPE" IS '编辑页类型（0抽屉 1弹框）';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."FUNCTION_AUTHOR" IS '生成功能作者';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."FUNCTION_NAME" IS '生成功能名';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."GEN_PATH" IS '生成路径（不填默认项目路径）';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."GEN_TYPE" IS '生成代码方式（0zip压缩包 1自定义路径）';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."MODULE_NAME" IS '生成模块名';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."OPTIONS" IS '其它生成选项';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."PACKAGE_NAME" IS '生成包路径';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."REMARK" IS '备注';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."SUB_TABLE_FK_NAME" IS '子表关联的外键名';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."SUB_TABLE_NAME" IS '关联子表的表名';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."TABLE_COMMENT" IS '表描述';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."TABLE_ID" IS '编号';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."TABLE_NAME" IS '表名称';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."TPL_CATEGORY" IS '使用的模板（crud单表操作 tree树表操作）';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."TPL_WEB_TYPE" IS '前端模板类型（element-ui模版 element-plus模版）';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "sqfast"."GEN_TABLE"."UPDATE_TIME" IS '更新时间';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526555595311612" ON "sqfast"."GEN_TABLE"("TABLE_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."GEN_TABLE_COLUMN"
(
"COLUMN_ID" BIGINT IDENTITY(528, 1) NOT NULL,
"TABLE_ID" BIGINT,
"COLUMN_NAME" VARCHAR(200),
"COLUMN_COMMENT" VARCHAR(500),
"COLUMN_TYPE" VARCHAR(100),
"JAVA_TYPE" VARCHAR(500),
"JAVA_FIELD" VARCHAR(200),
"IS_PK" CHAR(1),
"IS_INCREMENT" CHAR(1),
"IS_REQUIRED" CHAR(1),
"IS_INSERT" CHAR(1),
"IS_EDIT" CHAR(1),
"IS_LIST" CHAR(1),
"IS_QUERY" CHAR(1),
"QUERY_TYPE" VARCHAR(200) DEFAULT 'EQ',
"HTML_TYPE" VARCHAR(200),
"DICT_TYPE" VARCHAR(200) DEFAULT '',
"SORT" INT,
"CREATE_BY" VARCHAR(64) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"MAX_LENGTH" INT,
"MIN_LENGTH" INT,
NOT CLUSTER PRIMARY KEY("COLUMN_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."GEN_TABLE_COLUMN" IS '代码生成业务表字段';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."COLUMN_COMMENT" IS '列描述';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."COLUMN_ID" IS '编号';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."COLUMN_NAME" IS '列名称';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."COLUMN_TYPE" IS '列类型';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."DICT_TYPE" IS '字典类型';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."HTML_TYPE" IS '显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."IS_EDIT" IS '是否编辑字段（1是）';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."IS_INCREMENT" IS '是否自增（1是）';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."IS_INSERT" IS '是否为插入字段（1是）';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."IS_LIST" IS '是否列表字段（1是）';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."IS_PK" IS '是否主键（1是）';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."IS_QUERY" IS '是否查询字段（1是）';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."IS_REQUIRED" IS '是否必填（1是）';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."JAVA_FIELD" IS 'JAVA字段名';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."JAVA_TYPE" IS 'JAVA类型';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."MAX_LENGTH" IS '最大长度';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."MIN_LENGTH" IS '最小长度';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."QUERY_TYPE" IS '查询方式（等于、不等于、大于、小于、范围）';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."SORT" IS '排序';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."TABLE_ID" IS '归属表编号';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "sqfast"."GEN_TABLE_COLUMN"."UPDATE_TIME" IS '更新时间';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526555479095568" ON "sqfast"."GEN_TABLE_COLUMN"("COLUMN_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."QRTZ_BLOB_TRIGGERS"
(
"SCHED_NAME" VARCHAR(120) NOT NULL,
"TRIGGER_NAME" VARCHAR(200) NOT NULL,
"TRIGGER_GROUP" VARCHAR(200) NOT NULL,
"BLOB_DATA" BLOB,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
CONSTRAINT "QRTZ_BLOB_TRIGGERS_IBFK_1" FOREIGN KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "sqfast"."QRTZ_TRIGGERS"("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."QRTZ_BLOB_TRIGGERS" IS 'Blob类型的触发器表';
COMMENT ON COLUMN "sqfast"."QRTZ_BLOB_TRIGGERS"."BLOB_DATA" IS '存放持久化Trigger对象';
COMMENT ON COLUMN "sqfast"."QRTZ_BLOB_TRIGGERS"."SCHED_NAME" IS '调度名称';
COMMENT ON COLUMN "sqfast"."QRTZ_BLOB_TRIGGERS"."TRIGGER_GROUP" IS 'qrtz_triggers表trigger_group的外键';
COMMENT ON COLUMN "sqfast"."QRTZ_BLOB_TRIGGERS"."TRIGGER_NAME" IS 'qrtz_triggers表trigger_name的外键';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526555418529818" ON "sqfast"."QRTZ_BLOB_TRIGGERS"("SCHED_NAME" ASC,"TRIGGER_NAME" ASC,"TRIGGER_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."QRTZ_CALENDARS"
(
"SCHED_NAME" VARCHAR(120) NOT NULL,
"CALENDAR_NAME" VARCHAR(200) NOT NULL,
"CALENDAR" BLOB NOT NULL,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "CALENDAR_NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."QRTZ_CALENDARS" IS '日历信息表';
COMMENT ON COLUMN "sqfast"."QRTZ_CALENDARS"."CALENDAR" IS '存放持久化calendar对象';
COMMENT ON COLUMN "sqfast"."QRTZ_CALENDARS"."CALENDAR_NAME" IS '日历名称';
COMMENT ON COLUMN "sqfast"."QRTZ_CALENDARS"."SCHED_NAME" IS '调度名称';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526555392954192" ON "sqfast"."QRTZ_CALENDARS"("SCHED_NAME" ASC,"CALENDAR_NAME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."QRTZ_CRON_TRIGGERS"
(
"SCHED_NAME" VARCHAR(120) NOT NULL,
"TRIGGER_NAME" VARCHAR(200) NOT NULL,
"TRIGGER_GROUP" VARCHAR(200) NOT NULL,
"CRON_EXPRESSION" VARCHAR(200) NOT NULL,
"TIME_ZONE_ID" VARCHAR(80),
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
CONSTRAINT "QRTZ_CRON_TRIGGERS_IBFK_1" FOREIGN KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "sqfast"."QRTZ_TRIGGERS"("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."QRTZ_CRON_TRIGGERS" IS 'Cron类型的触发器表';
COMMENT ON COLUMN "sqfast"."QRTZ_CRON_TRIGGERS"."CRON_EXPRESSION" IS 'cron表达式';
COMMENT ON COLUMN "sqfast"."QRTZ_CRON_TRIGGERS"."SCHED_NAME" IS '调度名称';
COMMENT ON COLUMN "sqfast"."QRTZ_CRON_TRIGGERS"."TIME_ZONE_ID" IS '时区';
COMMENT ON COLUMN "sqfast"."QRTZ_CRON_TRIGGERS"."TRIGGER_GROUP" IS 'qrtz_triggers表trigger_group的外键';
COMMENT ON COLUMN "sqfast"."QRTZ_CRON_TRIGGERS"."TRIGGER_NAME" IS 'qrtz_triggers表trigger_name的外键';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526555318872120" ON "sqfast"."QRTZ_CRON_TRIGGERS"("SCHED_NAME" ASC,"TRIGGER_NAME" ASC,"TRIGGER_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."QRTZ_FIRED_TRIGGERS"
(
"SCHED_NAME" VARCHAR(120) NOT NULL,
"ENTRY_ID" VARCHAR(95) NOT NULL,
"TRIGGER_NAME" VARCHAR(200) NOT NULL,
"TRIGGER_GROUP" VARCHAR(200) NOT NULL,
"INSTANCE_NAME" VARCHAR(200) NOT NULL,
"FIRED_TIME" BIGINT NOT NULL,
"SCHED_TIME" BIGINT NOT NULL,
"PRIORITY" INT NOT NULL,
"STATE" VARCHAR(16) NOT NULL,
"JOB_NAME" VARCHAR(200),
"JOB_GROUP" VARCHAR(200),
"IS_NONCONCURRENT" VARCHAR(1),
"REQUESTS_RECOVERY" VARCHAR(1),
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "ENTRY_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."QRTZ_FIRED_TRIGGERS" IS '已触发的触发器表';
COMMENT ON COLUMN "sqfast"."QRTZ_FIRED_TRIGGERS"."ENTRY_ID" IS '调度器实例id';
COMMENT ON COLUMN "sqfast"."QRTZ_FIRED_TRIGGERS"."FIRED_TIME" IS '触发的时间';
COMMENT ON COLUMN "sqfast"."QRTZ_FIRED_TRIGGERS"."INSTANCE_NAME" IS '调度器实例名';
COMMENT ON COLUMN "sqfast"."QRTZ_FIRED_TRIGGERS"."IS_NONCONCURRENT" IS '是否并发';
COMMENT ON COLUMN "sqfast"."QRTZ_FIRED_TRIGGERS"."JOB_GROUP" IS '任务组名';
COMMENT ON COLUMN "sqfast"."QRTZ_FIRED_TRIGGERS"."JOB_NAME" IS '任务名称';
COMMENT ON COLUMN "sqfast"."QRTZ_FIRED_TRIGGERS"."PRIORITY" IS '优先级';
COMMENT ON COLUMN "sqfast"."QRTZ_FIRED_TRIGGERS"."REQUESTS_RECOVERY" IS '是否接受恢复执行';
COMMENT ON COLUMN "sqfast"."QRTZ_FIRED_TRIGGERS"."SCHED_NAME" IS '调度名称';
COMMENT ON COLUMN "sqfast"."QRTZ_FIRED_TRIGGERS"."SCHED_TIME" IS '定时器制定的时间';
COMMENT ON COLUMN "sqfast"."QRTZ_FIRED_TRIGGERS"."STATE" IS '状态';
COMMENT ON COLUMN "sqfast"."QRTZ_FIRED_TRIGGERS"."TRIGGER_GROUP" IS 'qrtz_triggers表trigger_group的外键';
COMMENT ON COLUMN "sqfast"."QRTZ_FIRED_TRIGGERS"."TRIGGER_NAME" IS 'qrtz_triggers表trigger_name的外键';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526555173805472" ON "sqfast"."QRTZ_FIRED_TRIGGERS"("SCHED_NAME" ASC,"ENTRY_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."QRTZ_JOB_DETAILS"
(
"SCHED_NAME" VARCHAR(120) NOT NULL,
"JOB_NAME" VARCHAR(200) NOT NULL,
"JOB_GROUP" VARCHAR(200) NOT NULL,
"DESCRIPTION" VARCHAR(250),
"JOB_CLASS_NAME" VARCHAR(250) NOT NULL,
"IS_DURABLE" VARCHAR(1) NOT NULL,
"IS_NONCONCURRENT" VARCHAR(1) NOT NULL,
"IS_UPDATE_DATA" VARCHAR(1) NOT NULL,
"REQUESTS_RECOVERY" VARCHAR(1) NOT NULL,
"JOB_DATA" BLOB,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "JOB_NAME", "JOB_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."QRTZ_JOB_DETAILS" IS '任务详细信息表';
COMMENT ON COLUMN "sqfast"."QRTZ_JOB_DETAILS"."DESCRIPTION" IS '相关介绍';
COMMENT ON COLUMN "sqfast"."QRTZ_JOB_DETAILS"."IS_DURABLE" IS '是否持久化';
COMMENT ON COLUMN "sqfast"."QRTZ_JOB_DETAILS"."IS_NONCONCURRENT" IS '是否并发';
COMMENT ON COLUMN "sqfast"."QRTZ_JOB_DETAILS"."IS_UPDATE_DATA" IS '是否更新数据';
COMMENT ON COLUMN "sqfast"."QRTZ_JOB_DETAILS"."JOB_CLASS_NAME" IS '执行任务类名称';
COMMENT ON COLUMN "sqfast"."QRTZ_JOB_DETAILS"."JOB_DATA" IS '存放持久化job对象';
COMMENT ON COLUMN "sqfast"."QRTZ_JOB_DETAILS"."JOB_GROUP" IS '任务组名';
COMMENT ON COLUMN "sqfast"."QRTZ_JOB_DETAILS"."JOB_NAME" IS '任务名称';
COMMENT ON COLUMN "sqfast"."QRTZ_JOB_DETAILS"."REQUESTS_RECOVERY" IS '是否接受恢复执行';
COMMENT ON COLUMN "sqfast"."QRTZ_JOB_DETAILS"."SCHED_NAME" IS '调度名称';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526555092984440" ON "sqfast"."QRTZ_JOB_DETAILS"("SCHED_NAME" ASC,"JOB_NAME" ASC,"JOB_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."QRTZ_LOCKS"
(
"SCHED_NAME" VARCHAR(120) NOT NULL,
"LOCK_NAME" VARCHAR(40) NOT NULL,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "LOCK_NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."QRTZ_LOCKS" IS '存储的悲观锁信息表';
COMMENT ON COLUMN "sqfast"."QRTZ_LOCKS"."LOCK_NAME" IS '悲观锁名称';
COMMENT ON COLUMN "sqfast"."QRTZ_LOCKS"."SCHED_NAME" IS '调度名称';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526555063875284" ON "sqfast"."QRTZ_LOCKS"("SCHED_NAME" ASC,"LOCK_NAME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."QRTZ_PAUSED_TRIGGER_GRPS"
(
"SCHED_NAME" VARCHAR(120) NOT NULL,
"TRIGGER_GROUP" VARCHAR(200) NOT NULL,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."QRTZ_PAUSED_TRIGGER_GRPS" IS '暂停的触发器表';
COMMENT ON COLUMN "sqfast"."QRTZ_PAUSED_TRIGGER_GRPS"."SCHED_NAME" IS '调度名称';
COMMENT ON COLUMN "sqfast"."QRTZ_PAUSED_TRIGGER_GRPS"."TRIGGER_GROUP" IS 'qrtz_triggers表trigger_group的外键';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526555020540286" ON "sqfast"."QRTZ_PAUSED_TRIGGER_GRPS"("SCHED_NAME" ASC,"TRIGGER_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."QRTZ_SCHEDULER_STATE"
(
"SCHED_NAME" VARCHAR(120) NOT NULL,
"INSTANCE_NAME" VARCHAR(200) NOT NULL,
"LAST_CHECKIN_TIME" BIGINT NOT NULL,
"CHECKIN_INTERVAL" BIGINT NOT NULL,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "INSTANCE_NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."QRTZ_SCHEDULER_STATE" IS '调度器状态表';
COMMENT ON COLUMN "sqfast"."QRTZ_SCHEDULER_STATE"."CHECKIN_INTERVAL" IS '检查间隔时间';
COMMENT ON COLUMN "sqfast"."QRTZ_SCHEDULER_STATE"."INSTANCE_NAME" IS '实例名称';
COMMENT ON COLUMN "sqfast"."QRTZ_SCHEDULER_STATE"."LAST_CHECKIN_TIME" IS '上次检查时间';
COMMENT ON COLUMN "sqfast"."QRTZ_SCHEDULER_STATE"."SCHED_NAME" IS '调度名称';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526554962198246" ON "sqfast"."QRTZ_SCHEDULER_STATE"("SCHED_NAME" ASC,"INSTANCE_NAME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."QRTZ_SIMPLE_TRIGGERS"
(
"SCHED_NAME" VARCHAR(120) NOT NULL,
"TRIGGER_NAME" VARCHAR(200) NOT NULL,
"TRIGGER_GROUP" VARCHAR(200) NOT NULL,
"REPEAT_COUNT" BIGINT NOT NULL,
"REPEAT_INTERVAL" BIGINT NOT NULL,
"TIMES_TRIGGERED" BIGINT NOT NULL,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
CONSTRAINT "QRTZ_SIMPLE_TRIGGERS_IBFK_1" FOREIGN KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "sqfast"."QRTZ_TRIGGERS"("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."QRTZ_SIMPLE_TRIGGERS" IS '简单触发器的信息表';
COMMENT ON COLUMN "sqfast"."QRTZ_SIMPLE_TRIGGERS"."REPEAT_COUNT" IS '重复的次数统计';
COMMENT ON COLUMN "sqfast"."QRTZ_SIMPLE_TRIGGERS"."REPEAT_INTERVAL" IS '重复的间隔时间';
COMMENT ON COLUMN "sqfast"."QRTZ_SIMPLE_TRIGGERS"."SCHED_NAME" IS '调度名称';
COMMENT ON COLUMN "sqfast"."QRTZ_SIMPLE_TRIGGERS"."TIMES_TRIGGERED" IS '已经触发的次数';
COMMENT ON COLUMN "sqfast"."QRTZ_SIMPLE_TRIGGERS"."TRIGGER_GROUP" IS 'qrtz_triggers表trigger_group的外键';
COMMENT ON COLUMN "sqfast"."QRTZ_SIMPLE_TRIGGERS"."TRIGGER_NAME" IS 'qrtz_triggers表trigger_name的外键';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526554920793844" ON "sqfast"."QRTZ_SIMPLE_TRIGGERS"("SCHED_NAME" ASC,"TRIGGER_NAME" ASC,"TRIGGER_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."QRTZ_SIMPROP_TRIGGERS"
(
"SCHED_NAME" VARCHAR(120) NOT NULL,
"TRIGGER_NAME" VARCHAR(200) NOT NULL,
"TRIGGER_GROUP" VARCHAR(200) NOT NULL,
"STR_PROP_1" VARCHAR(512),
"STR_PROP_2" VARCHAR(512),
"STR_PROP_3" VARCHAR(512),
"INT_PROP_1" INT,
"INT_PROP_2" INT,
"LONG_PROP_1" BIGINT,
"LONG_PROP_2" BIGINT,
"DEC_PROP_1" DEC(13,4),
"DEC_PROP_2" DEC(13,4),
"BOOL_PROP_1" VARCHAR(1),
"BOOL_PROP_2" VARCHAR(1),
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
CONSTRAINT "QRTZ_SIMPROP_TRIGGERS_IBFK_1" FOREIGN KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "sqfast"."QRTZ_TRIGGERS"("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."QRTZ_SIMPROP_TRIGGERS" IS '同步机制的行锁表';
COMMENT ON COLUMN "sqfast"."QRTZ_SIMPROP_TRIGGERS"."BOOL_PROP_1" IS 'Boolean类型的trigger的第一个参数';
COMMENT ON COLUMN "sqfast"."QRTZ_SIMPROP_TRIGGERS"."BOOL_PROP_2" IS 'Boolean类型的trigger的第二个参数';
COMMENT ON COLUMN "sqfast"."QRTZ_SIMPROP_TRIGGERS"."DEC_PROP_1" IS 'decimal类型的trigger的第一个参数';
COMMENT ON COLUMN "sqfast"."QRTZ_SIMPROP_TRIGGERS"."DEC_PROP_2" IS 'decimal类型的trigger的第二个参数';
COMMENT ON COLUMN "sqfast"."QRTZ_SIMPROP_TRIGGERS"."INT_PROP_1" IS 'int类型的trigger的第一个参数';
COMMENT ON COLUMN "sqfast"."QRTZ_SIMPROP_TRIGGERS"."INT_PROP_2" IS 'int类型的trigger的第二个参数';
COMMENT ON COLUMN "sqfast"."QRTZ_SIMPROP_TRIGGERS"."LONG_PROP_1" IS 'long类型的trigger的第一个参数';
COMMENT ON COLUMN "sqfast"."QRTZ_SIMPROP_TRIGGERS"."LONG_PROP_2" IS 'long类型的trigger的第二个参数';
COMMENT ON COLUMN "sqfast"."QRTZ_SIMPROP_TRIGGERS"."SCHED_NAME" IS '调度名称';
COMMENT ON COLUMN "sqfast"."QRTZ_SIMPROP_TRIGGERS"."STR_PROP_1" IS 'String类型的trigger的第一个参数';
COMMENT ON COLUMN "sqfast"."QRTZ_SIMPROP_TRIGGERS"."STR_PROP_2" IS 'String类型的trigger的第二个参数';
COMMENT ON COLUMN "sqfast"."QRTZ_SIMPROP_TRIGGERS"."STR_PROP_3" IS 'String类型的trigger的第三个参数';
COMMENT ON COLUMN "sqfast"."QRTZ_SIMPROP_TRIGGERS"."TRIGGER_GROUP" IS 'qrtz_triggers表trigger_group的外键';
COMMENT ON COLUMN "sqfast"."QRTZ_SIMPROP_TRIGGERS"."TRIGGER_NAME" IS 'qrtz_triggers表trigger_name的外键';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526554788105636" ON "sqfast"."QRTZ_SIMPROP_TRIGGERS"("SCHED_NAME" ASC,"TRIGGER_NAME" ASC,"TRIGGER_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."QRTZ_TRIGGERS"
(
"SCHED_NAME" VARCHAR(120) NOT NULL,
"TRIGGER_NAME" VARCHAR(200) NOT NULL,
"TRIGGER_GROUP" VARCHAR(200) NOT NULL,
"JOB_NAME" VARCHAR(200) NOT NULL,
"JOB_GROUP" VARCHAR(200) NOT NULL,
"DESCRIPTION" VARCHAR(250),
"NEXT_FIRE_TIME" BIGINT,
"PREV_FIRE_TIME" BIGINT,
"PRIORITY" INT,
"TRIGGER_STATE" VARCHAR(16) NOT NULL,
"TRIGGER_TYPE" VARCHAR(8) NOT NULL,
"START_TIME" BIGINT NOT NULL,
"END_TIME" BIGINT,
"CALENDAR_NAME" VARCHAR(200),
"MISFIRE_INSTR" SMALLINT,
"JOB_DATA" BLOB,
NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
CONSTRAINT "QRTZ_TRIGGERS_IBFK_1" FOREIGN KEY("SCHED_NAME", "JOB_NAME", "JOB_GROUP") REFERENCES "sqfast"."QRTZ_JOB_DETAILS"("SCHED_NAME", "JOB_NAME", "JOB_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."QRTZ_TRIGGERS" IS '触发器详细信息表';
COMMENT ON COLUMN "sqfast"."QRTZ_TRIGGERS"."CALENDAR_NAME" IS '日程表名称';
COMMENT ON COLUMN "sqfast"."QRTZ_TRIGGERS"."DESCRIPTION" IS '相关介绍';
COMMENT ON COLUMN "sqfast"."QRTZ_TRIGGERS"."END_TIME" IS '结束时间';
COMMENT ON COLUMN "sqfast"."QRTZ_TRIGGERS"."JOB_DATA" IS '存放持久化job对象';
COMMENT ON COLUMN "sqfast"."QRTZ_TRIGGERS"."JOB_GROUP" IS 'qrtz_job_details表job_group的外键';
COMMENT ON COLUMN "sqfast"."QRTZ_TRIGGERS"."JOB_NAME" IS 'qrtz_job_details表job_name的外键';
COMMENT ON COLUMN "sqfast"."QRTZ_TRIGGERS"."MISFIRE_INSTR" IS '补偿执行的策略';
COMMENT ON COLUMN "sqfast"."QRTZ_TRIGGERS"."NEXT_FIRE_TIME" IS '上一次触发时间（毫秒）';
COMMENT ON COLUMN "sqfast"."QRTZ_TRIGGERS"."PREV_FIRE_TIME" IS '下一次触发时间（默认为-1表示不触发）';
COMMENT ON COLUMN "sqfast"."QRTZ_TRIGGERS"."PRIORITY" IS '优先级';
COMMENT ON COLUMN "sqfast"."QRTZ_TRIGGERS"."SCHED_NAME" IS '调度名称';
COMMENT ON COLUMN "sqfast"."QRTZ_TRIGGERS"."START_TIME" IS '开始时间';
COMMENT ON COLUMN "sqfast"."QRTZ_TRIGGERS"."TRIGGER_GROUP" IS '触发器所属组的名字';
COMMENT ON COLUMN "sqfast"."QRTZ_TRIGGERS"."TRIGGER_NAME" IS '触发器的名字';
COMMENT ON COLUMN "sqfast"."QRTZ_TRIGGERS"."TRIGGER_STATE" IS '触发器状态';
COMMENT ON COLUMN "sqfast"."QRTZ_TRIGGERS"."TRIGGER_TYPE" IS '触发器的类型';


CREATE OR REPLACE  INDEX "sqfast"."SCHED_NAME" ON "sqfast"."QRTZ_TRIGGERS"("SCHED_NAME" ASC,"JOB_NAME" ASC,"JOB_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526554666138330" ON "sqfast"."QRTZ_TRIGGERS"("SCHED_NAME" ASC,"TRIGGER_NAME" ASC,"TRIGGER_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."SYS_CONFIG"
(
"ID" INT NOT NULL,
"CONFIG_NAME" VARCHAR(100) DEFAULT '',
"CONFIG_KEY" VARCHAR(100) DEFAULT '',
"CONFIG_VALUE" VARCHAR(500) DEFAULT '',
"CONFIG_TYPE" CHAR(1) DEFAULT 'N',
"CREATE_BY" VARCHAR(64) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500),
"DEL_FLAG" CHAR(1) DEFAULT '0',
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."SYS_CONFIG" IS '参数配置表';
COMMENT ON COLUMN "sqfast"."SYS_CONFIG"."ID" IS '参数主键';
COMMENT ON COLUMN "sqfast"."SYS_CONFIG"."CONFIG_KEY" IS '参数键名';
COMMENT ON COLUMN "sqfast"."SYS_CONFIG"."CONFIG_NAME" IS '参数名称';
COMMENT ON COLUMN "sqfast"."SYS_CONFIG"."CONFIG_TYPE" IS '系统内置（Y是 N否）';
COMMENT ON COLUMN "sqfast"."SYS_CONFIG"."CONFIG_VALUE" IS '参数键值';
COMMENT ON COLUMN "sqfast"."SYS_CONFIG"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "sqfast"."SYS_CONFIG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "sqfast"."SYS_CONFIG"."DEL_FLAG" IS '删除标志（0代表存在 1代表删除）';
COMMENT ON COLUMN "sqfast"."SYS_CONFIG"."REMARK" IS '备注';
COMMENT ON COLUMN "sqfast"."SYS_CONFIG"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "sqfast"."SYS_CONFIG"."UPDATE_TIME" IS '更新时间';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526554582969008" ON "sqfast"."SYS_CONFIG"("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."SYS_DEPT"
(
"ID" BIGINT NOT NULL,
"PARENT_ID" BIGINT DEFAULT 0,
"ANCESTORS" VARCHAR(50) DEFAULT '',
"ENG_NAME" VARCHAR(200),
"DEPT_NAME" VARCHAR(30) DEFAULT '',
"ORDER_NUM" INT DEFAULT 0,
"LEADER" VARCHAR(20),
"PHONE" VARCHAR(11),
"EMAIL" VARCHAR(50),
"DEP_TYPE" VARCHAR(20),
"STATUS" CHAR(1) DEFAULT '0',
"DEL_FLAG" CHAR(1) DEFAULT '0',
"CREATE_BY" VARCHAR(64) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."SYS_DEPT" IS '机构表';
COMMENT ON COLUMN "sqfast"."SYS_DEPT"."ANCESTORS" IS '祖级列表';
COMMENT ON COLUMN "sqfast"."SYS_DEPT"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "sqfast"."SYS_DEPT"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "sqfast"."SYS_DEPT"."DEL_FLAG" IS '删除标志（0代表存在 1代表删除）';
COMMENT ON COLUMN "sqfast"."SYS_DEPT"."DEP_TYPE" IS '机构类型';
COMMENT ON COLUMN "sqfast"."SYS_DEPT"."ID" IS '机构id';
COMMENT ON COLUMN "sqfast"."SYS_DEPT"."DEPT_NAME" IS '机构名称';
COMMENT ON COLUMN "sqfast"."SYS_DEPT"."EMAIL" IS '邮箱';
COMMENT ON COLUMN "sqfast"."SYS_DEPT"."ENG_NAME" IS '英文名称';
COMMENT ON COLUMN "sqfast"."SYS_DEPT"."LEADER" IS '负责人';
COMMENT ON COLUMN "sqfast"."SYS_DEPT"."ORDER_NUM" IS '显示顺序';
COMMENT ON COLUMN "sqfast"."SYS_DEPT"."PARENT_ID" IS '父机构id';
COMMENT ON COLUMN "sqfast"."SYS_DEPT"."PHONE" IS '联系电话';
COMMENT ON COLUMN "sqfast"."SYS_DEPT"."STATUS" IS '机构状态（0正常 1停用）';
COMMENT ON COLUMN "sqfast"."SYS_DEPT"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "sqfast"."SYS_DEPT"."UPDATE_TIME" IS '更新时间';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526554455007674" ON "sqfast"."SYS_DEPT"("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."SYS_DICT_DATA"
(
"ID" BIGINT NOT NULL,
"DICT_SORT" INT DEFAULT 0,
"DICT_LABEL" VARCHAR(100) DEFAULT '',
"DICT_VALUE" VARCHAR(100) DEFAULT '',
"DICT_TYPE" VARCHAR(100) DEFAULT '',
"CSS_CLASS" VARCHAR(100),
"LIST_CLASS" VARCHAR(100),
"IS_DEFAULT" CHAR(1) DEFAULT 'N',
"STATUS" CHAR(1) DEFAULT '0',
"CREATE_BY" VARCHAR(64) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500),
"DEL_FLAG" CHAR(1) DEFAULT '0',
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."SYS_DICT_DATA" IS '字典数据表';
COMMENT ON COLUMN "sqfast"."SYS_DICT_DATA"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "sqfast"."SYS_DICT_DATA"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "sqfast"."SYS_DICT_DATA"."CSS_CLASS" IS '样式属性（其他样式扩展）';
COMMENT ON COLUMN "sqfast"."SYS_DICT_DATA"."ID" IS '字典编码';
COMMENT ON COLUMN "sqfast"."SYS_DICT_DATA"."DICT_LABEL" IS '字典标签';
COMMENT ON COLUMN "sqfast"."SYS_DICT_DATA"."DICT_SORT" IS '字典排序';
COMMENT ON COLUMN "sqfast"."SYS_DICT_DATA"."DICT_TYPE" IS '字典类型';
COMMENT ON COLUMN "sqfast"."SYS_DICT_DATA"."DICT_VALUE" IS '字典键值';
COMMENT ON COLUMN "sqfast"."SYS_DICT_DATA"."IS_DEFAULT" IS '是否默认（Y是 N否）';
COMMENT ON COLUMN "sqfast"."SYS_DICT_DATA"."LIST_CLASS" IS '表格回显样式';
COMMENT ON COLUMN "sqfast"."SYS_DICT_DATA"."REMARK" IS '备注';
COMMENT ON COLUMN "sqfast"."SYS_DICT_DATA"."DEL_FLAG" IS '删除标志（0代表存在 1代表删除）';
COMMENT ON COLUMN "sqfast"."SYS_DICT_DATA"."STATUS" IS '状态（0正常 1停用）';
COMMENT ON COLUMN "sqfast"."SYS_DICT_DATA"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "sqfast"."SYS_DICT_DATA"."UPDATE_TIME" IS '更新时间';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526554380880378" ON "sqfast"."SYS_DICT_DATA"("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."SYS_DICT_TYPE"
(
"ID" BIGINT NOT NULL,
"DICT_NAME" VARCHAR(100) DEFAULT '',
"DICT_TYPE" VARCHAR(100) DEFAULT '',
"STATUS" CHAR(1) DEFAULT '0',
"CREATE_BY" VARCHAR(64) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500),
"DEL_FLAG" CHAR(1) DEFAULT '0',
NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "DICT_TYPE" UNIQUE("DICT_TYPE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."SYS_DICT_TYPE" IS '字典类型表';
COMMENT ON COLUMN "sqfast"."SYS_DICT_TYPE"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "sqfast"."SYS_DICT_TYPE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "sqfast"."SYS_DICT_TYPE"."ID" IS '字典主键';
COMMENT ON COLUMN "sqfast"."SYS_DICT_TYPE"."DICT_NAME" IS '字典名称';
COMMENT ON COLUMN "sqfast"."SYS_DICT_TYPE"."DICT_TYPE" IS '字典类型';
COMMENT ON COLUMN "sqfast"."SYS_DICT_TYPE"."REMARK" IS '备注';
COMMENT ON COLUMN "sqfast"."SYS_DICT_TYPE"."DEL_FLAG" IS '删除标志（0代表存在 1代表删除）';
COMMENT ON COLUMN "sqfast"."SYS_DICT_TYPE"."STATUS" IS '状态（0正常 1停用）';
COMMENT ON COLUMN "sqfast"."SYS_DICT_TYPE"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "sqfast"."SYS_DICT_TYPE"."UPDATE_TIME" IS '更新时间';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526554335108346" ON "sqfast"."SYS_DICT_TYPE"("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."SYS_JOB"
(
"JOB_ID" BIGINT IDENTITY(100, 1) NOT NULL,
"JOB_NAME" VARCHAR(64) DEFAULT '' NOT NULL,
"JOB_GROUP" VARCHAR(64) DEFAULT 'DEFAULT' NOT NULL,
"INVOKE_TARGET" VARCHAR(500) NOT NULL,
"CRON_EXPRESSION" VARCHAR(255) DEFAULT '',
"MISFIRE_POLICY" VARCHAR(20) DEFAULT '3',
"CONCURRENT" CHAR(1) DEFAULT '1',
"STATUS" CHAR(1) DEFAULT '0',
"CREATE_BY" VARCHAR(64) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500) DEFAULT '',
NOT CLUSTER PRIMARY KEY("JOB_ID", "JOB_NAME", "JOB_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."SYS_JOB" IS '定时任务调度表';
COMMENT ON COLUMN "sqfast"."SYS_JOB"."CONCURRENT" IS '是否并发执行（0允许 1禁止）';
COMMENT ON COLUMN "sqfast"."SYS_JOB"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "sqfast"."SYS_JOB"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "sqfast"."SYS_JOB"."CRON_EXPRESSION" IS 'cron执行表达式';
COMMENT ON COLUMN "sqfast"."SYS_JOB"."INVOKE_TARGET" IS '调用目标字符串';
COMMENT ON COLUMN "sqfast"."SYS_JOB"."JOB_GROUP" IS '任务组名';
COMMENT ON COLUMN "sqfast"."SYS_JOB"."JOB_ID" IS '任务ID';
COMMENT ON COLUMN "sqfast"."SYS_JOB"."JOB_NAME" IS '任务名称';
COMMENT ON COLUMN "sqfast"."SYS_JOB"."MISFIRE_POLICY" IS '计划执行错误策略（1立即执行 2执行一次 3放弃执行）';
COMMENT ON COLUMN "sqfast"."SYS_JOB"."REMARK" IS '备注信息';
COMMENT ON COLUMN "sqfast"."SYS_JOB"."STATUS" IS '状态（0正常 1暂停）';
COMMENT ON COLUMN "sqfast"."SYS_JOB"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "sqfast"."SYS_JOB"."UPDATE_TIME" IS '更新时间';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526554239543090" ON "sqfast"."SYS_JOB"("JOB_ID" ASC,"JOB_NAME" ASC,"JOB_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."SYS_JOB_LOG"
(
"JOB_LOG_ID" BIGINT IDENTITY(1, 1) NOT NULL,
"JOB_NAME" VARCHAR(64) NOT NULL,
"JOB_GROUP" VARCHAR(64) NOT NULL,
"INVOKE_TARGET" VARCHAR(500) NOT NULL,
"JOB_MESSAGE" VARCHAR(500),
"STATUS" CHAR(1) DEFAULT '0',
"EXCEPTION_INFO" VARCHAR(2000) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("JOB_LOG_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."SYS_JOB_LOG" IS '定时任务调度日志表';
COMMENT ON COLUMN "sqfast"."SYS_JOB_LOG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "sqfast"."SYS_JOB_LOG"."EXCEPTION_INFO" IS '异常信息';
COMMENT ON COLUMN "sqfast"."SYS_JOB_LOG"."INVOKE_TARGET" IS '调用目标字符串';
COMMENT ON COLUMN "sqfast"."SYS_JOB_LOG"."JOB_GROUP" IS '任务组名';
COMMENT ON COLUMN "sqfast"."SYS_JOB_LOG"."JOB_LOG_ID" IS '任务日志ID';
COMMENT ON COLUMN "sqfast"."SYS_JOB_LOG"."JOB_MESSAGE" IS '日志信息';
COMMENT ON COLUMN "sqfast"."SYS_JOB_LOG"."JOB_NAME" IS '任务名称';
COMMENT ON COLUMN "sqfast"."SYS_JOB_LOG"."STATUS" IS '执行状态（0正常 1失败）';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526554202910362" ON "sqfast"."SYS_JOB_LOG"("JOB_LOG_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."SYS_LOGININFOR"
(
"INFO_ID" BIGINT NOT NULL,
"USER_NAME" VARCHAR(50) DEFAULT '',
"IPADDR" VARCHAR(128) DEFAULT '',
"LOGIN_LOCATION" VARCHAR(255) DEFAULT '',
"BROWSER" VARCHAR(50) DEFAULT '',
"OS" VARCHAR(50) DEFAULT '',
"STATUS" CHAR(1) DEFAULT '0',
"MSG" VARCHAR(255) DEFAULT '',
"LOGIN_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("INFO_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."SYS_LOGININFOR" IS '系统访问记录';
COMMENT ON COLUMN "sqfast"."SYS_LOGININFOR"."BROWSER" IS '浏览器类型';
COMMENT ON COLUMN "sqfast"."SYS_LOGININFOR"."INFO_ID" IS '访问ID';
COMMENT ON COLUMN "sqfast"."SYS_LOGININFOR"."IPADDR" IS '登录IP地址';
COMMENT ON COLUMN "sqfast"."SYS_LOGININFOR"."LOGIN_LOCATION" IS '登录地点';
COMMENT ON COLUMN "sqfast"."SYS_LOGININFOR"."LOGIN_TIME" IS '访问时间';
COMMENT ON COLUMN "sqfast"."SYS_LOGININFOR"."MSG" IS '提示消息';
COMMENT ON COLUMN "sqfast"."SYS_LOGININFOR"."OS" IS '操作系统';
COMMENT ON COLUMN "sqfast"."SYS_LOGININFOR"."STATUS" IS '登录状态（0成功 1失败）';
COMMENT ON COLUMN "sqfast"."SYS_LOGININFOR"."USER_NAME" IS '用户账号';


CREATE OR REPLACE  INDEX "sqfast"."IDX_SYS_LOGININFOR_LT" ON "sqfast"."SYS_LOGININFOR"("LOGIN_TIME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "sqfast"."IDX_SYS_LOGININFOR_S" ON "sqfast"."SYS_LOGININFOR"("STATUS" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526554116891860" ON "sqfast"."SYS_LOGININFOR"("INFO_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."SYS_MENU"
(
"ID" BIGINT NOT NULL,
"MENU_NAME" VARCHAR(50) NOT NULL,
"PARENT_ID" BIGINT DEFAULT 0,
"ORDER_NUM" INT DEFAULT 0,
"PATH" VARCHAR(200) DEFAULT '',
"COMPONENT" VARCHAR(255),
"QUERY" VARCHAR(255),
"IS_FRAME" INT DEFAULT 1,
"IS_CACHE" INT DEFAULT 0,
"MENU_TYPE" CHAR(1) DEFAULT '',
"VISIBLE" CHAR(1) DEFAULT '0',
"STATUS" CHAR(1) DEFAULT '0',
"PERMS" VARCHAR(100),
"ICON" VARCHAR(100) DEFAULT '#',
"CREATE_BY" VARCHAR(64) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500) DEFAULT '',
"DEL_FLAG" CHAR(1) DEFAULT '0',
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."SYS_MENU" IS '菜单权限表';
COMMENT ON COLUMN "sqfast"."SYS_MENU"."COMPONENT" IS '组件路径';
COMMENT ON COLUMN "sqfast"."SYS_MENU"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "sqfast"."SYS_MENU"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "sqfast"."SYS_MENU"."DEL_FLAG" IS '删除标志（0代表存在 1代表删除）';
COMMENT ON COLUMN "sqfast"."SYS_MENU"."ICON" IS '菜单图标';
COMMENT ON COLUMN "sqfast"."SYS_MENU"."IS_CACHE" IS '是否缓存（0缓存 1不缓存）';
COMMENT ON COLUMN "sqfast"."SYS_MENU"."IS_FRAME" IS '是否为外链（0是 1否）';
COMMENT ON COLUMN "sqfast"."SYS_MENU"."ID" IS '菜单ID';
COMMENT ON COLUMN "sqfast"."SYS_MENU"."MENU_NAME" IS '菜单名称';
COMMENT ON COLUMN "sqfast"."SYS_MENU"."MENU_TYPE" IS '菜单类型（M目录 C菜单 F按钮）';
COMMENT ON COLUMN "sqfast"."SYS_MENU"."ORDER_NUM" IS '显示顺序';
COMMENT ON COLUMN "sqfast"."SYS_MENU"."PARENT_ID" IS '父菜单ID';
COMMENT ON COLUMN "sqfast"."SYS_MENU"."PATH" IS '路由地址';
COMMENT ON COLUMN "sqfast"."SYS_MENU"."PERMS" IS '权限标识';
COMMENT ON COLUMN "sqfast"."SYS_MENU"."QUERY" IS '路由参数';
COMMENT ON COLUMN "sqfast"."SYS_MENU"."REMARK" IS '备注';
COMMENT ON COLUMN "sqfast"."SYS_MENU"."STATUS" IS '菜单状态（0正常 1停用）';
COMMENT ON COLUMN "sqfast"."SYS_MENU"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "sqfast"."SYS_MENU"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "sqfast"."SYS_MENU"."VISIBLE" IS '菜单状态（0显示 1隐藏）';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526553942557340" ON "sqfast"."SYS_MENU"("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."SYS_NOTICE"
(
"ID" INT NOT NULL,
"NOTICE_TITLE" VARCHAR(50) NOT NULL,
"NOTICE_TYPE" CHAR(1) NOT NULL,
"NOTICE_CONTENT" BLOB,
"STATUS" CHAR(1) DEFAULT '0',
"CREATE_BY" VARCHAR(64) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(255),
"DEL_FLAG" CHAR(1) DEFAULT '0',
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."SYS_NOTICE" IS '通知公告表';
COMMENT ON COLUMN "sqfast"."SYS_NOTICE"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "sqfast"."SYS_NOTICE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "sqfast"."SYS_NOTICE"."NOTICE_CONTENT" IS '公告内容';
COMMENT ON COLUMN "sqfast"."SYS_NOTICE"."ID" IS '公告ID';
COMMENT ON COLUMN "sqfast"."SYS_NOTICE"."NOTICE_TITLE" IS '公告标题';
COMMENT ON COLUMN "sqfast"."SYS_NOTICE"."NOTICE_TYPE" IS '公告类型（1通知 2公告）';
COMMENT ON COLUMN "sqfast"."SYS_NOTICE"."REMARK" IS '备注';
COMMENT ON COLUMN "sqfast"."SYS_NOTICE"."STATUS" IS '公告状态（0正常 1关闭）';
COMMENT ON COLUMN "sqfast"."SYS_NOTICE"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "sqfast"."SYS_NOTICE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "sqfast"."SYS_NOTICE"."DEL_FLAG" IS '删除标志（0代表存在 1代表删除）';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526553866758424" ON "sqfast"."SYS_NOTICE"("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."SYS_OPER_LOG"
(
"OPER_ID" BIGINT NOT NULL,
"TITLE" VARCHAR(50) DEFAULT '',
"BUSINESS_TYPE" INT DEFAULT 0,
"METHOD" VARCHAR(100) DEFAULT '',
"REQUEST_METHOD" VARCHAR(10) DEFAULT '',
"OPERATOR_TYPE" INT DEFAULT 0,
"OPER_NAME" VARCHAR(50) DEFAULT '',
"DEPT_NAME" VARCHAR(50) DEFAULT '',
"OPER_URL" VARCHAR(255) DEFAULT '',
"OPER_IP" VARCHAR(128) DEFAULT '',
"OPER_LOCATION" VARCHAR(255) DEFAULT '',
"OPER_PARAM" VARCHAR(2000) DEFAULT '',
"JSON_RESULT" VARCHAR(2000) DEFAULT '',
"STATUS" INT DEFAULT 0,
"ERROR_MSG" VARCHAR(2000) DEFAULT '',
"OPER_TIME" TIMESTAMP(0),
"COST_TIME" BIGINT DEFAULT 0,
NOT CLUSTER PRIMARY KEY("OPER_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."SYS_OPER_LOG" IS '操作日志记录';
COMMENT ON COLUMN "sqfast"."SYS_OPER_LOG"."BUSINESS_TYPE" IS '业务类型（0其它 1新增 2修改 3删除）';
COMMENT ON COLUMN "sqfast"."SYS_OPER_LOG"."COST_TIME" IS '消耗时间';
COMMENT ON COLUMN "sqfast"."SYS_OPER_LOG"."DEPT_NAME" IS '机构名称';
COMMENT ON COLUMN "sqfast"."SYS_OPER_LOG"."ERROR_MSG" IS '错误消息';
COMMENT ON COLUMN "sqfast"."SYS_OPER_LOG"."JSON_RESULT" IS '返回参数';
COMMENT ON COLUMN "sqfast"."SYS_OPER_LOG"."METHOD" IS '方法名称';
COMMENT ON COLUMN "sqfast"."SYS_OPER_LOG"."OPER_ID" IS '日志主键';
COMMENT ON COLUMN "sqfast"."SYS_OPER_LOG"."OPER_IP" IS '主机地址';
COMMENT ON COLUMN "sqfast"."SYS_OPER_LOG"."OPER_LOCATION" IS '操作地点';
COMMENT ON COLUMN "sqfast"."SYS_OPER_LOG"."OPER_NAME" IS '操作人员';
COMMENT ON COLUMN "sqfast"."SYS_OPER_LOG"."OPER_PARAM" IS '请求参数';
COMMENT ON COLUMN "sqfast"."SYS_OPER_LOG"."OPER_TIME" IS '操作时间';
COMMENT ON COLUMN "sqfast"."SYS_OPER_LOG"."OPER_URL" IS '请求URL';
COMMENT ON COLUMN "sqfast"."SYS_OPER_LOG"."OPERATOR_TYPE" IS '操作类别（0其它 1后台用户 2手机端用户）';
COMMENT ON COLUMN "sqfast"."SYS_OPER_LOG"."REQUEST_METHOD" IS '请求方式';
COMMENT ON COLUMN "sqfast"."SYS_OPER_LOG"."STATUS" IS '操作状态（0正常 1异常）';
COMMENT ON COLUMN "sqfast"."SYS_OPER_LOG"."TITLE" IS '模块标题';


CREATE OR REPLACE  INDEX "sqfast"."IDX_SYS_OPER_LOG_S" ON "sqfast"."SYS_OPER_LOG"("STATUS" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "sqfast"."IDX_SYS_OPER_LOG_OT" ON "sqfast"."SYS_OPER_LOG"("OPER_TIME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "sqfast"."IDX_SYS_OPER_LOG_BT" ON "sqfast"."SYS_OPER_LOG"("BUSINESS_TYPE" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526553747436784" ON "sqfast"."SYS_OPER_LOG"("OPER_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."SYS_POST"
(
"ID" BIGINT NOT NULL,
"POST_CODE" VARCHAR(64) NOT NULL,
"POST_NAME" VARCHAR(50) NOT NULL,
"POST_SORT" INT NOT NULL,
"STATUS" CHAR(1) NOT NULL,
"CREATE_BY" VARCHAR(64) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500),
"DEL_FLAG" CHAR(1) DEFAULT '0',
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."SYS_POST" IS '岗位信息表';
COMMENT ON COLUMN "sqfast"."SYS_POST"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "sqfast"."SYS_POST"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "sqfast"."SYS_POST"."POST_CODE" IS '岗位编码';
COMMENT ON COLUMN "sqfast"."SYS_POST"."ID" IS '岗位ID';
COMMENT ON COLUMN "sqfast"."SYS_POST"."POST_NAME" IS '岗位名称';
COMMENT ON COLUMN "sqfast"."SYS_POST"."POST_SORT" IS '显示顺序';
COMMENT ON COLUMN "sqfast"."SYS_POST"."REMARK" IS '备注';
COMMENT ON COLUMN "sqfast"."SYS_POST"."STATUS" IS '状态（0正常 1停用）';
COMMENT ON COLUMN "sqfast"."SYS_POST"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "sqfast"."SYS_POST"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "sqfast"."SYS_POST"."DEL_FLAG" IS '删除标志（0代表存在 1代表删除）';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526553602423040" ON "sqfast"."SYS_POST"("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."SYS_ROLE"
(
"ID" BIGINT NOT NULL,
"DEPT_ID" BIGINT,
"ROLE_NAME" VARCHAR(30) NOT NULL,
"ROLE_KEY" VARCHAR(100) NOT NULL,
"ROLE_SORT" INT NOT NULL,
"DATA_SCOPE" CHAR(1) DEFAULT '1',
"MENU_CHECK_STRICTLY" TINYINT DEFAULT 1,
"DEPT_CHECK_STRICTLY" TINYINT DEFAULT 1,
"STATUS" CHAR(1) NOT NULL,
"DEL_FLAG" CHAR(1) DEFAULT '0',
"CREATE_BY" VARCHAR(64) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."SYS_ROLE" IS '角色信息表';
COMMENT ON COLUMN "sqfast"."SYS_ROLE"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "sqfast"."SYS_ROLE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "sqfast"."SYS_ROLE"."DATA_SCOPE" IS '数据范围（1：全部数据权限 2：自定数据权限 3：本机构数据权限 4：本机构及以下数据权限）';
COMMENT ON COLUMN "sqfast"."SYS_ROLE"."DEL_FLAG" IS '删除标志（0代表存在 1代表删除）';
COMMENT ON COLUMN "sqfast"."SYS_ROLE"."DEPT_CHECK_STRICTLY" IS '机构树选择项是否关联显示';
COMMENT ON COLUMN "sqfast"."SYS_ROLE"."DEPT_ID" IS '机构ID';
COMMENT ON COLUMN "sqfast"."SYS_ROLE"."MENU_CHECK_STRICTLY" IS '菜单树选择项是否关联显示';
COMMENT ON COLUMN "sqfast"."SYS_ROLE"."REMARK" IS '备注';
COMMENT ON COLUMN "sqfast"."SYS_ROLE"."ID" IS '角色ID';
COMMENT ON COLUMN "sqfast"."SYS_ROLE"."ROLE_KEY" IS '角色权限字符串';
COMMENT ON COLUMN "sqfast"."SYS_ROLE"."ROLE_NAME" IS '角色名称';
COMMENT ON COLUMN "sqfast"."SYS_ROLE"."ROLE_SORT" IS '显示顺序';
COMMENT ON COLUMN "sqfast"."SYS_ROLE"."STATUS" IS '角色状态（0正常 1停用）';
COMMENT ON COLUMN "sqfast"."SYS_ROLE"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "sqfast"."SYS_ROLE"."UPDATE_TIME" IS '更新时间';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526553483137236" ON "sqfast"."SYS_ROLE"("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."SYS_ROLE_DEPT"
(
"ROLE_ID" BIGINT NOT NULL,
"DEPT_ID" BIGINT NOT NULL,
NOT CLUSTER PRIMARY KEY("ROLE_ID", "DEPT_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."SYS_ROLE_DEPT" IS '角色和机构关联表';
COMMENT ON COLUMN "sqfast"."SYS_ROLE_DEPT"."DEPT_ID" IS '机构ID';
COMMENT ON COLUMN "sqfast"."SYS_ROLE_DEPT"."ROLE_ID" IS '角色ID';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526553457845758" ON "sqfast"."SYS_ROLE_DEPT"("ROLE_ID" ASC,"DEPT_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."SYS_ROLE_MENU"
(
"ROLE_ID" BIGINT NOT NULL,
"MENU_ID" BIGINT NOT NULL,
NOT CLUSTER PRIMARY KEY("ROLE_ID", "MENU_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."SYS_ROLE_MENU" IS '角色和菜单关联表';
COMMENT ON COLUMN "sqfast"."SYS_ROLE_MENU"."MENU_ID" IS '菜单ID';
COMMENT ON COLUMN "sqfast"."SYS_ROLE_MENU"."ROLE_ID" IS '角色ID';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526553400768740" ON "sqfast"."SYS_ROLE_MENU"("ROLE_ID" ASC,"MENU_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."SYS_USER"
(
"ID" BIGINT NOT NULL,
"DEPT_ID" BIGINT,
"USER_NAME" VARCHAR(30) NOT NULL,
"NICK_NAME" VARCHAR(30) NOT NULL,
"USER_TYPE" VARCHAR(2) DEFAULT '00',
"EMAIL" VARCHAR(50) DEFAULT '',
"PHONENUMBER" VARCHAR(11) DEFAULT '',
"SEX" CHAR(1) DEFAULT '0',
"AVATAR" VARCHAR(100) DEFAULT '',
"PASSWORD" VARCHAR(100) DEFAULT '',
"STATUS" CHAR(1) DEFAULT '0',
"DEL_FLAG" CHAR(1) DEFAULT '0',
"LOGIN_IP" VARCHAR(128) DEFAULT '',
"LOGIN_DATE" TIMESTAMP(0),
"CREATE_BY" VARCHAR(64) DEFAULT '',
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_BY" VARCHAR(64) DEFAULT '',
"UPDATE_TIME" TIMESTAMP(0),
"REMARK" VARCHAR(500),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."SYS_USER" IS '用户信息表';
COMMENT ON COLUMN "sqfast"."SYS_USER"."AVATAR" IS '头像地址';
COMMENT ON COLUMN "sqfast"."SYS_USER"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "sqfast"."SYS_USER"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "sqfast"."SYS_USER"."DEL_FLAG" IS '删除标志（0代表存在 1代表删除）';
COMMENT ON COLUMN "sqfast"."SYS_USER"."DEPT_ID" IS '机构ID';
COMMENT ON COLUMN "sqfast"."SYS_USER"."EMAIL" IS '用户邮箱';
COMMENT ON COLUMN "sqfast"."SYS_USER"."LOGIN_DATE" IS '最后登录时间';
COMMENT ON COLUMN "sqfast"."SYS_USER"."LOGIN_IP" IS '最后登录IP';
COMMENT ON COLUMN "sqfast"."SYS_USER"."NICK_NAME" IS '用户昵称';
COMMENT ON COLUMN "sqfast"."SYS_USER"."PASSWORD" IS '密码';
COMMENT ON COLUMN "sqfast"."SYS_USER"."PHONENUMBER" IS '手机号码';
COMMENT ON COLUMN "sqfast"."SYS_USER"."REMARK" IS '备注';
COMMENT ON COLUMN "sqfast"."SYS_USER"."SEX" IS '用户性别（0男 1女 2未知）';
COMMENT ON COLUMN "sqfast"."SYS_USER"."STATUS" IS '帐号状态（0正常 1停用）';
COMMENT ON COLUMN "sqfast"."SYS_USER"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "sqfast"."SYS_USER"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "sqfast"."SYS_USER"."ID" IS '用户ID';
COMMENT ON COLUMN "sqfast"."SYS_USER"."USER_NAME" IS '用户账号';
COMMENT ON COLUMN "sqfast"."SYS_USER"."USER_TYPE" IS '用户类型（00系统用户）';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526553238757626" ON "sqfast"."SYS_USER"("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."SYS_USER_POST"
(
"USER_ID" BIGINT NOT NULL,
"POST_ID" BIGINT NOT NULL,
NOT CLUSTER PRIMARY KEY("USER_ID", "POST_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."SYS_USER_POST" IS '用户与岗位关联表';
COMMENT ON COLUMN "sqfast"."SYS_USER_POST"."POST_ID" IS '岗位ID';
COMMENT ON COLUMN "sqfast"."SYS_USER_POST"."USER_ID" IS '用户ID';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."INDEX16526553216973650" ON "sqfast"."SYS_USER_POST"("USER_ID" ASC,"POST_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "sqfast"."SYS_USER_ROLE"
(
"USER_ID" BIGINT NOT NULL,
"ROLE_ID" BIGINT NOT NULL,
NOT CLUSTER PRIMARY KEY("USER_ID", "ROLE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "sqfast"."SYS_USER_ROLE" IS '用户和角色关联表';
COMMENT ON COLUMN "sqfast"."SYS_USER_ROLE"."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN "sqfast"."SYS_USER_ROLE"."USER_ID" IS '用户ID';


CREATE OR REPLACE UNIQUE  INDEX "sqfast"."PRIMARY" ON "sqfast"."SYS_USER_ROLE"("USER_ID" ASC,"ROLE_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

