<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.sq</groupId>
        <artifactId>hgtruck-goods</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>sq-system</artifactId>

    <description>
        system系统模块
    </description>

    <!--仓库路径 -->
    <repositories>
        <repository>
            <id>nexus</id>
            <name>Public Repository of sq</name>
            <url>http://10.11.20.32:8081/repository/maven-public/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>

        <repository>
            <id>public</id>
            <name>aliyun nexus</name>
            <url>https://maven.aliyun.com/repository/public</url>
            <releases>
                <enabled>true</enabled>
            </releases>
        </repository>
    </repositories>

    <dependencies>

        <!-- 通用工具-->
        <dependency>
            <groupId>com.sq</groupId>
            <artifactId>sq-common</artifactId>
        </dependency>

    </dependencies>

</project>
